name: Docker CI

on:
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
        - name: Clone repository
          uses: actions/checkout@v3
          with:
            submodules: true
        - name: Setup dotnet
          uses: actions/setup-dotnet@v2
        - name: Login Docker
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build container
          run: docker build -t translate-bot --progress plain .
        - name: Tag container
          run: docker tag translate-bot ${{ secrets.DOCKER_USER }}/translate-bot:latest
        - name: Push Docker
          run: docker push ${{ secrets.DOCKER_USER }}/translate-bot:latest
        - name: Login Heroku
          run: docker login --username=_ --password=${{ secrets.HEROKU_TOKEN }} registry.heroku.com
        - name: Build Heroku
          run: docker build -t registry.heroku.com/${{ secrets.APP_NAME }}/web --progress plain .
        - name: Push Heroku
          run: docker push registry.heroku.com/${{ secrets.APP_NAME }}/web

