name: Deploy Heroku

on:
  push:
    branches:
        - main
    
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
        - name: Clone repository
          uses: actions/checkout@v3
          with:
            submodules: true
        - name: Setup dotnet
          uses: actions/setup-dotnet@v2
        - name: Login Docker
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build container
          run: docker build -t translate-bot --progress plain .
        - name: Tag container
          run: docker tag translate-bot ${{ secrets.DOCKER_USER }}/translate-bot:latest
        - name: Login Heroku
          run: docker login --username=_ --password=${{ secrets.HEROKU_TOKEN }} registry.heroku.com
        - name: Build Heroku
          run: docker build -t registry.heroku.com/${{ secrets.APP_NAME }}/worker --progress plain .
        - name: Push Heroku
          run: docker push registry.heroku.com/${{ secrets.APP_NAME }}/worker
        - name: Install Heroku
          run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - name: Login Heroku
          shell: bash
          env:
            HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
          run: |
            touch ~/.netrc
            echo "machine api.heroku.com" >> ~/.netrc
            echo "  login misha.zaverkin@gmail.com" >> ~/.netrc
            echo "  password $HEROKU_TOKEN" >> ~/.netrc
            echo "machine git.heroku.com" >> ~/.netrc
            echo "  login misha.zaverkin@gmail.com" >> ~/.netrc
            echo "  password $HEROKU_TOKEN" >> ~/.netrc
        - name: Deploy container
          run: heroku container:release worker -a ${{ secrets.APP_NAME }}
