name: Deploy Heroku develop

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Clone repository
          uses: actions/checkout@v3
          with:
            submodules: true
        - name: Setup dotnet
          uses: actions/setup-dotnet@v2
        - name: Login Heroku
          run: docker login --username=_ --password=${{ secrets.HEROKU_TOKEN }} registry.heroku.com
        - name: Build Heroku
          run: docker build -t registry.heroku.com/${{ secrets.APP_NAME }}-develop/worker --progress plain .
        - name: Tag container
          run: docker tag translate-bot ${{ secrets.DOCKER_USER }}/translate-bot:latest
        - name: Push Heroku
          run: docker push registry.heroku.com/${{ secrets.APP_NAME }}-develop/worker
        - name: Install Heroku
          run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - name: Login Heroku
          shell: bash
          env:
            HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
          run: |
            touch ~/.netrc
            echo "machine api.heroku.com" >> ~/.netrc
            echo "  login misha.zaverkin@gmail.com" >> ~/.netrc
            echo "  password $HEROKU_TOKEN" >> ~/.netrc
            echo "machine git.heroku.com" >> ~/.netrc
            echo "  login misha.zaverkin@gmail.com" >> ~/.netrc
            echo "  password $HEROKU_TOKEN" >> ~/.netrc
        - name: Deploy container
          run: heroku container:release worker -a ${{ secrets.APP_NAME }}-develop
