name: Upload to Docker Hub

on:
  push:
    branches:
        - main
  workflow_dispatch:
    
jobs:
#  lint:
#    uses: ./.github/workflows/lint.yml
  deploy:
    runs-on: ubuntu-latest
#    needs: lint
    steps:
        - run: |
            echo "$PWD"
            ls
            echo "$GITHUB_WORKSPACE"
            echo "Test ${{ env.GITHUB_WORKSPACE }}"
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - run: |
            echo "$PWD"
            ls
            echo "$GITHUB_WORKSPACE"
            echo "Test ${{ env.GITHUB_WORKSPACE }}"
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - run: |
            echo "$PWD"
            ls
            echo "$GITHUB_WORKSPACE"
            echo "Test ${{ env.GITHUB_WORKSPACE }}"
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ${{ env.GITHUB_WORKSPACE }}
            file: Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: ${{ secrets.DOCKER_USER }}/translate-bot:latest
            cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/translate-bot:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKER_USER }}/translate-bot:buildcache,mode=max
#        - name: Login Heroku
#          run: docker login --username=_ --password=${{ secrets.HEROKU_TOKEN }} registry.heroku.com
#        - name: Build Heroku
#          run: docker build -t registry.heroku.com/${{ secrets.APP_NAME }}/worker --progress plain .
#        - name: Push Heroku
#          run: docker push registry.heroku.com/${{ secrets.APP_NAME }}/worker
#        - name: Install Heroku CLI
#          run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
#        - name: Login Heroku CLI
#          shell: bash
#          env:
#            HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
#          run: |
#            touch ~/.netrc
#            echo "machine api.heroku.com" >> ~/.netrc
#            echo "  login misha.zaverkin@gmail.com" >> ~/.netrc
#            echo "  password $HEROKU_TOKEN" >> ~/.netrc
#            echo "machine git.heroku.com" >> ~/.netrc
#            echo "  login misha.zaverkin@gmail.com" >> ~/.netrc
#            echo "  password $HEROKU_TOKEN" >> ~/.netrc
#        - name: Deploy container
#          run: heroku container:release worker -a ${{ secrets.APP_NAME }}
